//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomRover.AddBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check
    {
        public int id_check { get; set; }
        public int id_count { get; set; }
        public int id_uslugi { get; set; }
        public int id_dish { get; set; }
    
        public virtual Count Count { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        public virtual Spa_fitness Spa_fitness { get; set; }
    }
}
