//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomRover.AddBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int id_review { get; set; }
        public int id_guest { get; set; }
        public int rating { get; set; }
        public string comment { get; set; }
    
        public virtual Guest Guest { get; set; }
    }
}
