//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomRover.AddBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RGB_Uslugi
    {
        public int id_human { get; set; }
        public bool spa { get; set; }
        public bool fitnes { get; set; }
        public bool bar { get; set; }
        public bool restor { get; set; }
    }
}
